package nebula.simpletemplate;

import java.io.IOException;
import nebula.simpletemplate.Action;
import nebula.simpletemplate.STGroup;
import nebula.simpletemplate.CompiledST;

public class ActionComplier_anonymous__java_lang_String_0 implements Action {
	public void exec(STGroup paramSTGroup, CompiledST paramTemplateImpl, StringBuilder paramStringBuilder, Object[] paramArrayOfObject) throws IOException {
		paramStringBuilder.append("<html>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("<head>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("<title>");
		Object[] arrayOfObject = { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		arrayOfObject = new Object[] { (String) paramArrayOfObject[0] };
		paramArrayOfObject = arrayOfObject;
		paramStringBuilder.append("print(");
		paramStringBuilder.append((String) paramArrayOfObject[0]);
		paramStringBuilder.append(")");
		paramArrayOfObject = paramArrayOfObject;
		paramStringBuilder.append("</title>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("<body>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("<hr>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("</body>");
		paramStringBuilder.append("\r\n");
		paramStringBuilder.append("</html>");
	}
}
